services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  consumer:
    build: 
      context: consumer
    environment:
      - KAFKA_SOCKET_ADDRESS=kafka:9092
      - KAFKA_TOPIC=foo
    depends_on:
      - kafka
  producer:
    build:
      context: producer
    environment:
      - KAFKA_SOCKET_ADDRESS=kafka:9092
      - KAFKA_TOPIC=foo
    depends_on:
      - kafka